### ISSUE TITLE
Datenquelle etc

### ISSUE THREAD

**Issue by fabian-s** [nebnola/Dataviz#1]
Hi @nebnola, 

ich bin Dozent für Statistik an der LMU München und würde das evtl gerne nächsten Winter als Bsp in meine Vorlesung zu Deskriptiver Statistik einbauen.

1. Darf ich?
2. Kannst Du mir sagen wo & wann Du die Daten runtergeladen hast?

**Comment by fabian-s** [comment]
RE: Datenquellle: never mind, ich hätte einfach nur die Kommentare auf reddit runterscrollen müssen.....

**Comment by nebnola** [comment]
Ja, gern, das ist kein Problem. Datenquellen stehen auf Reddit. Ich habe ein paar Anpassungen machen müssen, zum Beispiel hat das Saarland nur eine Ausländerbehörde, also habe ich das als einen Landkreis behandelt.
